### ISSUE TITLE
Fully implement VobSub support

### ISSUE THREAD

**Issue by ecdye** [ecdye/macSubtitleOCR#7]
- [x] Add primary decoding support (#11)
- [x] Add MKV decoding support (#17)
- [x] Fix interlacing issues (#21)
- [x] Fix timestamp issues (#18)
